### ISSUE TITLE
Missing degreesToRadians()

### ISSUE THREAD

**Issue by sebastienFrance** [brandonskane/GeoLocation_Swift#1]
I think the following is missing, else it will not compile ;-)

extension Int {
    var degreesToRadians: Double { return Double(self) \* M_PI / 180 }
    var radiansToDegrees: Double { return Double(self) \* 180 / M_PI }
}

extension Double {
    var degreesToRadians: Double { return self \* M_PI / 180 }
    var radiansToDegrees: Double { return self \* 180 / M_PI }
}

**Comment by brandonskane** [comment]
Thank you. I extracted this out of my own project and forgot to include that. Its now added.

**Comment by sebastienFrance** [comment]
Thanks!
